namespace KeepLordWarriors;

public static class Constants
{
    public const float KeepHeight = 10f;
    public const float ArrowGravity = 3.5f;
    public const float ArrowVelocity = 6f;
    public const float ArrowWeakVelocity = 3f;
    public const float ArcherBaseCooldown = 10f;
    public const float ArcherBaseRange = 6f;
    public const float MageBaseRange = 5f;
    public const float ArcherSetupMaxTime = 1f;
    public const float ArcherSetupMinTime = .2f;
    public const int ArrowBaseDamage = 1;

    public static readonly string[] KeepNames =
    [
        "abbott",
        "abel",
        "adams",
        "addison",
        "adkins",
        "agent",
        "aldrich",
        "aldridge",
        "alford",
        "allen",
        "appleton",
        "arrington",
        "arwood",
        "atkins",
        "austin",
        "avery",
        "bailey",
        "baine",
        "baird",
        "baldwin",
        "bankston",
        "barker",
        "barnes",
        "barnett",
        "barry",
        "barton",
        "baughan",
        "beard",
        "beasley",
        "beck",
        "bell",
        "bennett",
        "berry",
        "bishop",
        "black",
        "blake",
        "blaxton",
        "blaylock",
        "blevins",
        "bonds",
        "boone",
        "boston",
        "botiler",
        "boyd",
        "bradford",
        "brannon",
        "brazeall",
        "brewer",
        "bridgeman",
        "brimer",
        "brooks",
        "brown",
        "bryant",
        "burdick",
        "burnet",
        "burns",
        "burrell",
        "byars",
        "bynum",
        "cagle",
        "cagner",
        "cain",
        "calvert",
        "campbell",
        "canada",
        "cantrell",
        "carroll",
        "carter",
        "cary",
        "casey",
        "cates",
        "chambers",
        "chappell",
        "chillcoat",
        "clark",
        "cline",
        "cole",
        "collman",
        "commens",
        "compton",
        "cooper",
        "cotton",
        "cowart",
        "cox",
        "cummings",
        "curtis",
        "davidson",
        "davis",
        "deason",
        "dempsey",
        "derrick",
        "dodd",
        "donough",
        "dorris",
        "doss",
        "dover",
        "downy",
        "dunahoo",
        "duncan",
        "dunlap",
        "dupre",
        "eaton",
        "eatton",
        "elliott",
        "ellis",
        "england",
        "estes",
        "evans",
        "ezell",
        "fair",
        "farley",
        "farris",
        "faught",
        "forester",
        "fowler",
        "freeman",
        "frost",
        "gamble",
        "ganes",
        "gardener",
        "garrison",
        "garson",
        "gentle",
        "george",
        "gibson",
        "gice",
        "gilbert",
        "glenn",
        "godsey",
        "goodwin",
        "gosset",
        "grantham",
        "grastey",
        "green",
        "griffin",
        "guest",
        "gunter",
        "guthrie",
        "hadder",
        "haines",
        "haley",
        "hamilton",
        "hampton",
        "hand",
        "harbin",
        "harmon",
        "harper",
        "harris",
        "hatchett",
        "haw",
        "haynes",
        "hays",
        "hebster",
        "hefner",
        "henderson",
        "hendon",
        "henson",
        "hewitt",
        "hicks",
        "hightower",
        "hiller",
        "hilton",
        "hinesley",
        "hix",
        "hogg",
        "holden",
        "holloway",
        "holt",
        "hood",
        "hoover",
        "hopson",
        "horton",
        "howard",
        "howells",
        "hudson",
        "hughes",
        "hyde",
        "ingle",
        "inmon",
        "isabell",
        "ivy",
        "jack",
        "jackson",
        "james",
        "jamison",
        "jeffries",
        "jenkins",
        "johnson",
        "kemp",
        "key",
        "kidd",
        "kiker",
        "kile",
        "kimbrell",
        "king",
        "knight",
        "knox",
        "lambert",
        "lane",
        "laneford",
        "laramore",
        "lawson",
        "lay",
        "league",
        "lewis",
        "little",
        "litton",
        "logan",
        "long",
        "looney",
        "love",
        "lovelady",
        "lovell",
        "lovett",
        "lynn",
        "manasco",
        "mann",
        "martin",
        "mathews",
        "mcclane",
        "mcclung",
        "mcclure",
        "mccolum",
        "mccoy",
        "mccue",
        "mccullan",
        "mccullar",
        "mcdaniel",
        "mcduff",
        "mckay",
        "mcnames",
        "mcneil",
        "mcnutt",
        "mellican",
        "merritt",
        "metcalf",
        "miles",
        "miller",
        "mitchell",
        "mobley",
        "moody",
        "mooney",
        "morgan",
        "morris",
        "motes",
        "mullins",
        "nelson",
        "nesmith",
        "newman",
        "nolen",
        "noles",
        "oden",
        "odom",
        "overton",
        "owsley",
        "pace",
        "painter",
        "parsons",
        "partain",
        "patek",
        "payne",
        "peak",
        "pearson",
        "pencard",
        "penn",
        "penyl",
        "perkins",
        "perry",
        "peters",
        "pittman",
        "plott",
        "poe",
        "pool",
        "posey",
        "pouder",
        "powell",
        "preston",
        "pugh",
        "pulliam",
        "purdy",
        "radford",
        "ramey",
        "ramie",
        "ray",
        "raynes",
        "reeves",
        "riddle",
        "rivers",
        "roberts",
        "robinson",
        "roden",
        "rollins",
        "romines",
        "ronow",
        "rowe",
        "rush",
        "russell",
        "rutledge",
        "sam",
        "samples",
        "sanford",
        "sarun",
        "scogin",
        "segars",
        "setton",
        "sexton",
        "shadix",
        "shain",
        "shank",
        "shelly",
        "shipman",
        "siddens",
        "simmons",
        "simpson",
        "sims",
        "slater",
        "smathers",
        "smith",
        "sneed",
        "south",
        "spain",
        "spane",
        "sparks",
        "staten",
        "steel",
        "stevens",
        "stewart",
        "stokes",
        "stone",
        "strange",
        "sunmers",
        "surin",
        "suttles",
        "swindle",
        "taberson",
        "tarbutton",
        "taylor",
        "teague",
        "tedford",
        "thomas",
        "thompson",
        "thornton",
        "tidwell",
        "tittle",
        "tubs",
        "tucker",
        "turner",
        "tyler",
        "ussery",
        "waid",
        "walker",
        "walston",
        "ward",
        "ware",
        "warren",
        "watson",
        "watts",
        "weaver",
        "webb",
        "welborn",
        "welsh",
        "west",
        "white",
        "whitman",
        "whitney",
        "whitten",
        "wiley",
        "willborn",
        "williams",
        "willis",
        "willson",
        "wilson",
        "wise",
        "woodley",
        "woods",
        "wooley",
        "wright",
        "york",
        "young",
    ];

    public static class TileCase
    {
        /*
            0000: Full water
            0001: Single corner
            0010: Single corner
            0011: Two adjacent
            0100: Single corner
            0101: Two adjacent
            0110: Two opposite corners
            0111: Three corners
            1000: Single corner
            1001: Two opposite corners
            1010: Two adjacent
            1011: Three corners
            1100: Two adjacent
            1101: Three corners
            1110: Three corners
            1111: Full land
        */

        public static uint FULL_WATER = 0;
        public static uint FULL_LAND = 15;
        public static readonly HashSet<uint> SINGLE_LAND_CORNERS =
            new HashSet<uint>([1, 2, 4, 8]);
        public static readonly HashSet<uint> TWO_LAND_ADJACENT =
            new HashSet<uint>([3, 5, 10, 12]);
        public static readonly HashSet<uint> TWO_LAND_OPPOSITE =
            new HashSet<uint>([6, 9]);
        public static readonly HashSet<uint> THREE_CORNERS =
            new HashSet<uint>([7, 11, 13, 14]);
    }

}